// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: proto/forester.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForesterMessage_ResponseStatus int32

const (
	ForesterMessage_SUCCESS ForesterMessage_ResponseStatus = 0
	ForesterMessage_ERROR   ForesterMessage_ResponseStatus = 1
)

// Enum value maps for ForesterMessage_ResponseStatus.
var (
	ForesterMessage_ResponseStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
	}
	ForesterMessage_ResponseStatus_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   1,
	}
)

func (x ForesterMessage_ResponseStatus) Enum() *ForesterMessage_ResponseStatus {
	p := new(ForesterMessage_ResponseStatus)
	*p = x
	return p
}

func (x ForesterMessage_ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForesterMessage_ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_forester_proto_enumTypes[0].Descriptor()
}

func (ForesterMessage_ResponseStatus) Type() protoreflect.EnumType {
	return &file_proto_forester_proto_enumTypes[0]
}

func (x ForesterMessage_ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForesterMessage_ResponseStatus.Descriptor instead.
func (ForesterMessage_ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_forester_proto_rawDescGZIP(), []int{0, 0}
}

type ForesterMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  ForesterMessage_ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=forester.ForesterMessage_ResponseStatus" json:"status,omitempty"`
	Message string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ForesterMessage) Reset() {
	*x = ForesterMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forester_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForesterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForesterMessage) ProtoMessage() {}

func (x *ForesterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forester_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForesterMessage.ProtoReflect.Descriptor instead.
func (*ForesterMessage) Descriptor() ([]byte, []int) {
	return file_proto_forester_proto_rawDescGZIP(), []int{0}
}

func (x *ForesterMessage) GetStatus() ForesterMessage_ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ForesterMessage_SUCCESS
}

func (x *ForesterMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GET
type ForesterGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ForesterGetRequest) Reset() {
	*x = ForesterGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forester_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForesterGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForesterGetRequest) ProtoMessage() {}

func (x *ForesterGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forester_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForesterGetRequest.ProtoReflect.Descriptor instead.
func (*ForesterGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_forester_proto_rawDescGZIP(), []int{1}
}

func (x *ForesterGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ForesterGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *ForesterMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Value   *string          `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *ForesterGetResponse) Reset() {
	*x = ForesterGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forester_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForesterGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForesterGetResponse) ProtoMessage() {}

func (x *ForesterGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forester_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForesterGetResponse.ProtoReflect.Descriptor instead.
func (*ForesterGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_forester_proto_rawDescGZIP(), []int{2}
}

func (x *ForesterGetResponse) GetMessage() *ForesterMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ForesterGetResponse) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// SET
type ForesterSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ForesterSetRequest) Reset() {
	*x = ForesterSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forester_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForesterSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForesterSetRequest) ProtoMessage() {}

func (x *ForesterSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forester_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForesterSetRequest.ProtoReflect.Descriptor instead.
func (*ForesterSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_forester_proto_rawDescGZIP(), []int{3}
}

func (x *ForesterSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ForesterSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ForesterSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *ForesterMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ForesterSetResponse) Reset() {
	*x = ForesterSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forester_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForesterSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForesterSetResponse) ProtoMessage() {}

func (x *ForesterSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forester_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForesterSetResponse.ProtoReflect.Descriptor instead.
func (*ForesterSetResponse) Descriptor() ([]byte, []int) {
	return file_proto_forester_proto_rawDescGZIP(), []int{4}
}

func (x *ForesterSetResponse) GetMessage() *ForesterMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// DELETE
type ForesterDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ForesterDeleteRequest) Reset() {
	*x = ForesterDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forester_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForesterDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForesterDeleteRequest) ProtoMessage() {}

func (x *ForesterDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forester_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForesterDeleteRequest.ProtoReflect.Descriptor instead.
func (*ForesterDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_forester_proto_rawDescGZIP(), []int{5}
}

func (x *ForesterDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ForesterDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *ForesterMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Deleted bool             `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *ForesterDeleteResponse) Reset() {
	*x = ForesterDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forester_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForesterDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForesterDeleteResponse) ProtoMessage() {}

func (x *ForesterDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forester_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForesterDeleteResponse.ProtoReflect.Descriptor instead.
func (*ForesterDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_forester_proto_rawDescGZIP(), []int{6}
}

func (x *ForesterDeleteResponse) GetMessage() *ForesterMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ForesterDeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_proto_forester_proto protoreflect.FileDescriptor

var file_proto_forester_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72,
	0x22, 0x97, 0x01, 0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x28, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x22, 0x26, 0x0a, 0x12, 0x46, 0x6f,
	0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x6f, 0x0a, 0x13, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x6f, 0x72,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x3c, 0x0a, 0x12, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x4a, 0x0a, 0x13, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x6f, 0x72, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a,
	0x15, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x67, 0x0a, 0x16, 0x46, 0x6f, 0x72, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x46,
	0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x32, 0xe5, 0x01, 0x0a, 0x08, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x44,
	0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x46,
	0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x66, 0x6f,
	0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x6f, 0x72, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_forester_proto_rawDescOnce sync.Once
	file_proto_forester_proto_rawDescData = file_proto_forester_proto_rawDesc
)

func file_proto_forester_proto_rawDescGZIP() []byte {
	file_proto_forester_proto_rawDescOnce.Do(func() {
		file_proto_forester_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_forester_proto_rawDescData)
	})
	return file_proto_forester_proto_rawDescData
}

var file_proto_forester_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_forester_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_forester_proto_goTypes = []interface{}{
	(ForesterMessage_ResponseStatus)(0), // 0: forester.ForesterMessage.ResponseStatus
	(*ForesterMessage)(nil),             // 1: forester.ForesterMessage
	(*ForesterGetRequest)(nil),          // 2: forester.ForesterGetRequest
	(*ForesterGetResponse)(nil),         // 3: forester.ForesterGetResponse
	(*ForesterSetRequest)(nil),          // 4: forester.ForesterSetRequest
	(*ForesterSetResponse)(nil),         // 5: forester.ForesterSetResponse
	(*ForesterDeleteRequest)(nil),       // 6: forester.ForesterDeleteRequest
	(*ForesterDeleteResponse)(nil),      // 7: forester.ForesterDeleteResponse
}
var file_proto_forester_proto_depIdxs = []int32{
	0, // 0: forester.ForesterMessage.status:type_name -> forester.ForesterMessage.ResponseStatus
	1, // 1: forester.ForesterGetResponse.message:type_name -> forester.ForesterMessage
	1, // 2: forester.ForesterSetResponse.message:type_name -> forester.ForesterMessage
	1, // 3: forester.ForesterDeleteResponse.message:type_name -> forester.ForesterMessage
	2, // 4: forester.Forester.Get:input_type -> forester.ForesterGetRequest
	4, // 5: forester.Forester.Set:input_type -> forester.ForesterSetRequest
	6, // 6: forester.Forester.Delete:input_type -> forester.ForesterDeleteRequest
	3, // 7: forester.Forester.Get:output_type -> forester.ForesterGetResponse
	5, // 8: forester.Forester.Set:output_type -> forester.ForesterSetResponse
	7, // 9: forester.Forester.Delete:output_type -> forester.ForesterDeleteResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_forester_proto_init() }
func file_proto_forester_proto_init() {
	if File_proto_forester_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_forester_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForesterMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forester_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForesterGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forester_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForesterGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forester_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForesterSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forester_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForesterSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forester_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForesterDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forester_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForesterDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_forester_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_forester_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_forester_proto_goTypes,
		DependencyIndexes: file_proto_forester_proto_depIdxs,
		EnumInfos:         file_proto_forester_proto_enumTypes,
		MessageInfos:      file_proto_forester_proto_msgTypes,
	}.Build()
	File_proto_forester_proto = out.File
	file_proto_forester_proto_rawDesc = nil
	file_proto_forester_proto_goTypes = nil
	file_proto_forester_proto_depIdxs = nil
}
