// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: proto/lumberjack.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LumberjackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LumberjackRequest) Reset() {
	*x = LumberjackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lumberjack_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LumberjackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LumberjackRequest) ProtoMessage() {}

func (x *LumberjackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lumberjack_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LumberjackRequest.ProtoReflect.Descriptor instead.
func (*LumberjackRequest) Descriptor() ([]byte, []int) {
	return file_proto_lumberjack_proto_rawDescGZIP(), []int{0}
}

func (x *LumberjackRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LumberjackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful bool   `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LumberjackResponse) Reset() {
	*x = LumberjackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lumberjack_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LumberjackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LumberjackResponse) ProtoMessage() {}

func (x *LumberjackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lumberjack_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LumberjackResponse.ProtoReflect.Descriptor instead.
func (*LumberjackResponse) Descriptor() ([]byte, []int) {
	return file_proto_lumberjack_proto_rawDescGZIP(), []int{1}
}

func (x *LumberjackResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *LumberjackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_lumberjack_proto protoreflect.FileDescriptor

var file_proto_lumberjack_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61,
	0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x6a, 0x61, 0x63, 0x6b, 0x22, 0x29, 0x0a, 0x11, 0x4c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x4e, 0x0a, 0x12, 0x4c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x66, 0x75, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0xe7, 0x01, 0x0a, 0x0a, 0x4c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61, 0x63, 0x6b, 0x12, 0x46,
	0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61,
	0x63, 0x6b, 0x2e, 0x4c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61, 0x63,
	0x6b, 0x2e, 0x4c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x1d, 0x2e,
	0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61, 0x63, 0x6b, 0x2e, 0x4c, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x6a, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6c,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61, 0x63, 0x6b, 0x2e, 0x4c, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x6a, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x6a, 0x61, 0x63, 0x6b, 0x2e, 0x4c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x6a, 0x61, 0x63, 0x6b, 0x2e, 0x4c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6a, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lumberjack_proto_rawDescOnce sync.Once
	file_proto_lumberjack_proto_rawDescData = file_proto_lumberjack_proto_rawDesc
)

func file_proto_lumberjack_proto_rawDescGZIP() []byte {
	file_proto_lumberjack_proto_rawDescOnce.Do(func() {
		file_proto_lumberjack_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lumberjack_proto_rawDescData)
	})
	return file_proto_lumberjack_proto_rawDescData
}

var file_proto_lumberjack_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_lumberjack_proto_goTypes = []interface{}{
	(*LumberjackRequest)(nil),  // 0: lumberjack.LumberjackRequest
	(*LumberjackResponse)(nil), // 1: lumberjack.LumberjackResponse
}
var file_proto_lumberjack_proto_depIdxs = []int32{
	0, // 0: lumberjack.Lumberjack.Get:input_type -> lumberjack.LumberjackRequest
	0, // 1: lumberjack.Lumberjack.Set:input_type -> lumberjack.LumberjackRequest
	0, // 2: lumberjack.Lumberjack.Delete:input_type -> lumberjack.LumberjackRequest
	1, // 3: lumberjack.Lumberjack.Get:output_type -> lumberjack.LumberjackResponse
	1, // 4: lumberjack.Lumberjack.Set:output_type -> lumberjack.LumberjackResponse
	1, // 5: lumberjack.Lumberjack.Delete:output_type -> lumberjack.LumberjackResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lumberjack_proto_init() }
func file_proto_lumberjack_proto_init() {
	if File_proto_lumberjack_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lumberjack_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LumberjackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lumberjack_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LumberjackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lumberjack_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lumberjack_proto_goTypes,
		DependencyIndexes: file_proto_lumberjack_proto_depIdxs,
		MessageInfos:      file_proto_lumberjack_proto_msgTypes,
	}.Build()
	File_proto_lumberjack_proto = out.File
	file_proto_lumberjack_proto_rawDesc = nil
	file_proto_lumberjack_proto_goTypes = nil
	file_proto_lumberjack_proto_depIdxs = nil
}
